// Prototype values only; none of these numbers is production balance.
export const PROTOTYPE_CONFIG = {
  cycle: { testSeconds: 120, designSeconds: 21 * 24 * 60 * 60 },
  initial: {
    treasury: 10000,
    publicSentiment: 70,
    security: 70,
    prosperity: 60,
    aether: 12,
    monsterSaturation: 18,
    soldiers: { healthy: 40, wounded: 0, deadTotal: 0, standingAssigned: 0, emergencyAssigned: 0 },
  },
  aether: { basePerSecond: 0.6, perGrade: 0.12, unstable: 35, danger: 65, critical: 85 },
  saturation: {
    basePerSecond: 0.25,
    perGrade: 0.08,
    rising: 35,
    danger: 65,
    critical: 85,
    breakSpike: 35,
  },
  castle: { baseCapacity: 80, capacityPerLevel: 40 },
  recruitment: {
    costPerSoldier: 25,
    baseDuration: 2,
    secondsPerSoldier: 0.4,
    baseMax: 20,
    maxPerLevel: 10,
    defaultCount: 20,
  },
  standing: {
    effectPerSoldier: 0.035,
    efficiencyKnee: 35,
    exposureThreshold: 200,
    exposureByBand: [0.25, 0.5, 1, 1.5],
    deathEvery: 4,
    routeDuration: 12,
  },
  emergency: {
    costPerSoldier: 10,
    duration: 6,
    reductionPerSoldier: 2,
    woundedFraction: 0.15,
    deadFraction: 0.05,
    defaultCount: 10,
  },
  soldiers: { recoveryDuration: 30 },
  territory: {
    bands: { stable: 80, caution: 60, unrest: 30 },
    severity: { danger: 0.5, critical: 1, maximum: 1.4 },
    damage: { security: 0.3, prosperity: 0.15, sentiment: 0.06 },
    recovery: { security: 0.5, prosperity: 0.3, sentiment: 0.15 },
    delays: { security: 5, prosperity: 15, sentiment: 30 },
    aboveStableFactor: 0.2,
  },
  economy: {
    interval: 30,
    baseRevenue: 300,
    prosperityFloor: 0.25,
    prosperityFactor: 0.75,
    upkeepPerLiving: 2,
  },
  tax: {
    cooldown: 20,
    LOW: { revenueFactor: 0.6, recoveryFactor: 1.25, sentimentBurden: 0, prosperityBurden: 0 },
    NORMAL: { revenueFactor: 1, recoveryFactor: 1, sentimentBurden: 0, prosperityBurden: 0 },
    HIGH: {
      revenueFactor: 1.5,
      recoveryFactor: 0.85,
      sentimentBurden: 0.025,
      prosperityBurden: 0.015,
    },
  },
  policies: {
    cooldown: 20,
    slots: [1, 1, 2, 2, 3],
    definitions: {
      RESIDENT_RELIEF: { minLevel: 1, upkeep: 60, recovery: 'sentiment', factor: 1.6 },
      COMMERCE_SUPPORT: { minLevel: 2, upkeep: 60, recovery: 'prosperity', factor: 1.6 },
      SECURITY_SUPPORT: { minLevel: 1, upkeep: 60, recovery: 'security', factor: 1.6 },
      RECRUITMENT_SUPPORT: { minLevel: 2, upkeep: 50, costFactor: 0.8, timeFactor: 0.75 },
      RECONSTRUCTION: { minLevel: 4, upkeep: 100, recovery: 'all', factor: 1.5 },
    },
  },
  raid: { preparation: 1, duration: 5, reduction: 35 },
  contract: { reward: 1000, acceptanceDelay: 3, preparation: 1, duration: 5, reduction: 50 },
  wave: {
    duration: 8,
    sentimentDamage: 5,
    securityDamage: 8,
    prosperityDamage: 3,
    historyLimit: 12,
  },
  dev: { aetherStep: 20, saturationStep: 20, treasuryStep: 5000, timeStep: 30 },
  forecast: { testSeconds: 30, designSeconds: 86400 },
  logLimit: 12,
} as const;
